### PR TITLE
#2113 Pass through autoComplete to Form.Control in bootstrap-4

### PR DESCRIPTION
**Pull request by wegry**
### Reasons for making this change

[Please describe them here]

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
Thanks, can you add a test?

**Comment by wegry** [comment]
I've added one for `autoComplete` but not for `autocomplete`. I bumped the typescript dev dependency as well for `??` support in the tests.

**Comment by epicfaace** [comment]
Why close this PR?

--
Ashwin Ramaswami

**Comment by wegry** [comment]
@epicfaace https://github.com/rjsf-team/react-jsonschema-form/pull/2478#issuecomment-943449270

**Comment by epicfaace** [comment]
Okay, thanks. Best of luck with everything else!

--
Ashwin Ramaswami

**Pull request closed without merging**
