### PR TITLE
Localization for error messages

### LINKED ISSUE #1195: trouble with native compatibility with ajv-i18n
### Prerequisites

- [v] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [v] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [v] I'm providing a playground **codesandbox** (https://codesandbox.io/embed/vm3lz56j53?fontsize=14) demonstrating the issue.

### Description

Current realization of errors object incomes in **transformErrors** (https://react-jsonschema-form.readthedocs.io/en/latest/validation/#custom-error-messages) is incompatible with **ajv-i18n**  (https://github.com/epoberezkin/ajv-i18n)  

Since the AJV is used internally, it would be nice to ensure compatibility with AJV native i18n gear, especially considering that such compatibility is very simple to provide by expanding the "erorrs" with one property "keyword", the value for which already exists in members of incoming errors array members as "name" property.

See my playground sample (https://codesandbox.io/embed/vm3lz56j53?fontsize=14), where basic erros array normalizing by map for full compilibility with ajv-i18n localization function.

### Steps to Reproduce

1. Install and import localization (as sample - directly ru) function for ajv-i18n npm package
2. declare transformErrors fucntion where try to call localization function on basic (non modified) errors incoming argument
`
function transformErrors(errors) {
	localize_ru(errors);
	return i18n_normalized;
}
`
3. You will take error about missing required 'keyword' property in ajv-i18n
4. Then modify your transformErrors, where you previously normilize errors object with basic map
`
function transformErrors(errors) {
	const i18n_normalized = errors.map(e => ({ ...e, keyword: e.name }));
	localize_ru(i18n_normalized);
	return i18n_normalized;
}
`
5. errors messages are succsefully localizated with ajv-i18n

#### Expected behavior

The erros array members (objects) will have 'keyword' property (duplicated 'name' property value)

PS: May be 'name' property will be renamed to 'keyword' with concurrent refactoring thats usages in other project sources

#### Actual behavior

The erros array members (objects) not have 'keyword' property, and ajv-i18n localization gear crashes called with the current errors array as argumnet

### Version

current major - 1.2.1

### PR DESCRIPTION
**Pull request by IgorLesnevskiy**
### Reasons for making this change

Based on #846. Also, may close #1195.
@epicfaace @edi9999 @pieplu, take a look, please. English is not my mother tongue, so feel free to fix my language in the docs.

### Checklist

* [x] **I'm updating documentation**
  - [x] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [x] **I'm adding a new feature**
  - [x] I've updated the playground with example use of the feature

### CODE REVIEW

**Comment by seemike** [comment]
waiting so much for this feature!

**Comment by heath-freenome** [comment]
@epicfaace How goes the review on this? This feature will help many many people

**Comment by Ugolaf** [comment]
@epicfaace Hello, it is possible to fix those little conflicts in order to merge that feature?

**Comment by MedinaGitHub** [comment]
waiting so much for this feature!

**Comment by Ugolaf** [comment]
@epicfaace Do you need some help to merge that feature?

**Comment by epicfaace** [comment]
@Ugolaf , yeah, I haven't gotten a chance to do a review yet. Some things that would help is if someone could:
- do a short write-up of how the changes in the PR are designed
- look through the code to double-check everything is working properly (have sufficient tests, etc.)

This would really speed up my review, as these are the most time-consuming parts of any review.

**Comment by geohuz** [comment]
What is the progress on this issue, we are waiting for the feature to be released.

**Comment by v1talii-dev** [comment]
Игорь, спасибо вам за работу. Подскажите, когда планируется завершить работы по данному PR? Я очень поверхностно знаком с проектом, но если нужна какая-то помощь, готов ее предоставить. Очень хотелось бы иметь данную функциональность в продакшене.

**Comment by IgorLesnevskiy** [comment]
[v1talii-dev](https://github.com/v1talii-dev) я работал над этим полтора года назад, но, насколько вижу, фичу так и не проревьювили. я могу попробовать разобрать конфликты, но я вообще не помню что там было. кроме того, идет работа над версиюе 5.0.0, возможно там это уже реализовано из коробки.

@heath-freenome are planning to add this feature to the v5? I'm not sure whether I need to resolve the conflicts or not.

**Comment by heath-freenome** [comment]
@IgorLesnevskiy I am planning to provide an Ajv 8 version of a validator in the next week or so. I will provide similar capabilities as to what you provided here. I shall add you as a reviewer when I do. I don't believe that adding the feature to the Ajv v6 version of the validator makes sense since that version of Ajv is at the end-of-life.

**Comment by IgorLesnevskiy** [comment]
@heath-freenome sounds good, thank you!

**Comment by v1talii-dev** [comment]
@IgorLesnevskiy  @heath-freenome thank you all!

**Comment by heath-freenome** [comment]
@IgorLesnevskiy Ok, I can't seem to add you as a reviewer, but you can check out the new PR [here](https://github.com/rjsf-team/react-jsonschema-form/pull/3093)

**Comment by IgorLesnevskiy** [comment]
thank you! since there's no need in this mr anymore, I will close it.

**Pull request closed without merging**
