### PR TITLE
Allow to change additionalProperties to falsy values

### LINKED ISSUE #2462: additionalProperties [number] doesn't allow 0 values
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If I define a schema with "additionalProperties" with number values, I cannot set field to be 0 (gets set as empty string instead). All other numbers work fine.

**Edit:** This is also true of boolean additionalProperties set to false.

Example schema:
```
{
  "type": "object",
  "additionalProperties": {
    "type": "number"
  }
}
```

[playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJrZXkiOiIifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJ0eXBlIjoibnVtYmVyIn19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUifSwibGFzdE5hbWUiOnsidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

### Steps to Reproduce

- Add new key/value pair
- Defaults to 0, this is fine
- Change to non-zero value
- Try changing back to 0: Doesn't work

#### Expected behavior

Would like to set value to 0

#### Actual behavior

Field is set as empty string

### Version

2.5.1, though this also occurs in rjsf playground

### PR DESCRIPTION
**Pull request by verakruhliakova**
### Reasons for making this change

fixes #2462

Changing of additionalProperties to any falsy value (false, 0, null) leads to its unexpected conversion to an empty string.

Similar change is proposed here - #2463, but it requires tests and the PR has been stall for a little while. Feel free to cancel current PR, if the other one gets finished faster.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by epicfaace — APPROVED** [review]
Thank you @verakruhliakova !

**Comment by epicfaace** [comment]
Can you update from the latest master code and then add a line to the changelog with a description of the bug fixed as mentioned in (https://github.com/rjsf-team/react-jsonschema-form/blob/master/PULL_REQUEST_TEMPLATE.md)?

**Comment by verakruhliakova** [comment]
@epicfaace I've updated changelog and PR description. Thank you for reviewing!

**Review by epicfaace — APPROVED** [review]
Thanks!

**Pull request merged**
