### PR TITLE
(Chore) Bumped prettier to 2.1.1

### PR DESCRIPTION
**Pull request by jimmycallin**
### Reasons for making this change

Steps to create this PR:

1. Upgraded Prettier to 2.1.1.
2. Removed Prettier from core.
3. Created .prettierignore with dist, build, and coverage.
4. Removed redundant prettier config in package.json, since they are default in Prettier 2. 
5. Ran `npx prettier --write .`

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by jimmycallin** [comment]
The issue with this PR is that Prettier does no longer support Node < 10.

**Review by epicfaace — COMMENTED** [review]
Looks good -- it's especially good that we are able to format markdown too.

Could you also update the formatting checks and lint-staged commands to make sure they also include previously-ignored files, such as `.md` files and other config / js files that weren't included in these checks?

**Comment by jimmycallin** [comment]
@epicfaace Fixed! If you don't mind I would also like to remove the last special option (jsxBracketSameLine: true), so it's all default behavior.

**Comment by jimmycallin** [comment]
This one is stale and will need to be redone, closing.

**Pull request closed without merging**
