### PR TITLE
upgrade core-js

### PR DESCRIPTION
**Pull request by lygstate**
### Reasons for making this change

[Please describe them here]

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
Thanks -- can you update the core-js imports so they work with core js 3 instead of 2?

**Comment by natterstefan** [comment]
Hi,

I'm having trouble upgrading one of my projects to core-js@3 because this package imports/uses core-js@2 still - at least that's what I think is causing my issues.

image

With this babel.config.js:

image

There are this PR and https://github.com/rjsf-team/react-jsonschema-form/issues/1601, but doesn't look like much progress is made.

What needs to be done to make this work?

Thanks for your help and time.

**Comment by epicfaace** [comment]
@natterstefan we really just need someone to:
- upgrade core js in this library
- update imports to work with core js 3

Is this something you'd be interested in taking on?

**Comment by natterstefan** [comment]
Hi @epicfaace,

🤔 can you describe the tasks to get this done, please? Maybe I can allocate some time and try it. But first I need to understand how core-js is used in this lib, how it should be used, etc.

Thanks!

**Pull request closed without merging**
