### PR TITLE
fix(core): prevent from breaking when element to focus cannot be found

### PR DESCRIPTION
**Pull request by anthonycaron**
### Reasons for making this change

If for some reason the element to focus cannot be found when the validation fails and the `focusOnFirstError` prop is set, then it will throw an error.

### Checklist

- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR

### CODE REVIEW

**Comment by anthonycaron** [comment]
Hey @heath-freenome, I've created this really small PR because I had an issue with this in my project. I know it might be related to the fact that this happens in a custom widget and that somehow it's not using the right id in that widget to focus my element. But still if we can prevent it from breaking I guess it's good, and it might allow me to see the errors on my field anyway.

**Comment by heath-freenome** [comment]
@anthonycaron 

> Hey @heath-freenome, I've created this really small PR because I had an issue with this in my project. I know it might be related to the fact that this happens in a custom widget and that somehow it's not using the right id in that widget to focus my element. But still if we can prevent it from breaking I guess it's good, and it might allow me to see the errors on my field anyway.

I'm not sure why the snapshots needed to be updated, but they seem to be breaking the tests

**Comment by heath-freenome** [comment]
@anthonycaron I added the fix into my PR #3674 since I needed to do an emergency release anyway

**Comment by anthonycaron** [comment]
@heath-freenome Thank you !

**Pull request closed without merging**
