### PR TITLE
Setup material-ui tests

### LINKED ISSUE #1655: Create separate @rjsf/utils package
Original comment:
> I say we break out the utils package since it'll be better to maintain that way. If we need to make a path or minor to the utils package, in theory it shouldn't break anyones installs if they are using a `^` (i.e. `"@rjsf/utils": "^X.X.X"`).
> 
> For the fields and widgets, they should probably just be exposed in the root index file still so you can import them like so:
> ```tsx
> import { ArrayField } from '@rjsf/core';`
> ```
> 
> We would just need to _ensure_ tree shaking is set up correctly, that way they don't import everything from `@rjsf/core`.

_Originally posted by @chanceaclark in https://github.com/rjsf-team/react-jsonschema-form/pull/1642_

### PR DESCRIPTION
**Pull request by epicfaace**
### Reasons for making this change

Add tests to the material-ui theme so that it can be released.

Also, update the docs to discuss the themes in more detail.

Finally, refactors utils to be exported from the default @rjsf/core package so that they are properly transpiled -- fixes #1655 (this had to be done in order to get material-ui tests to work, so that's why both are done in the same PR)

So, previously an import would look like this:

```js
import { getDefaultRegistry } from "@rjsf/core/lib/utils";
```

Now you would need to do this:

```js
import { utils } from "@rjsf/core";
import { getDefaultRegistry } from utils;
```

Related: #1561 #1585 -- we'd have to get the theme documentation in first before merging these two PRs.

### CODE REVIEW

**Comment by heath-freenome** [comment]
Can we get a release with these fixes soon?

**Comment by epicfaace** [comment]
Soon!

**Comment by heath-freenome** [comment]
I really hope so, I'm starting to reach the point where this is almost completely blocking me

**Comment by Morriz** [comment]
Yes please, so that we may override `ArrayFieldTemplate` properly to inject our custom `AddButton` to use color='primary' instead of secondary.

**Pull request merged**
