### PR TITLE
Feat: Implements #297 request

### PR DESCRIPTION
**Pull request by Shubhcoder**
### Reasons for making this change

 I have added the code (with tests) to implement the feature requested in #297. 

### Checklist

- [x] **I'm updating documentation**
  - [x] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [x] **I'm adding a new feature**
  - [x] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
@Shubhcoder Thanks for this coding work. Due to some unfortunate copy/paste work done by previous theme authors, we actually have similar code in both the `antd` and `chakra-ui` themes. I've been meaning to take the time to refactor the duplicate (non-React component) based functions down into the `@rjsf/utils` package. Is this something you are willing to do as part of your fix?

**Comment by Shubhcoder** [comment]
Hi, @heath-freenome 

Sure, I would love to work on it.

**Comment by heath-freenome** [comment]
@Shubhcoder did you mean to close this?

**Comment by Shubhcoder** [comment]
Hi, @heath-freenome 

Yes, I will make another pr with the refactor code you were talking about.

**Pull request closed without merging**
