### PR TITLE
fix: playground now builds to dist, made upload work properly

### PR DESCRIPTION
**Pull request by heath-freenome**
### Reasons for making this change

Fixed playground deploy [broken](https://github.com/rjsf-team/react-jsonschema-form/actions/runs/3102029048/jobs/5024085173) by #3115

- Updated `ci.yml` to change `packages/playground/build` to `packages/playground/dist`

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
@ranihorev Ok, I believe this will fix things broken by #3115

**Review by ranihorev — APPROVED** [review]
Thanks for fixing this!

**Comment by ranihorev** [comment]
@heath-freenome I can also update vite to use `build` as the dist folder like the rest of the packages:
https://vitejs.dev/config/build-options.html#build-outdir

Let me know if you want me to do that

**Review by jacqueswho — APPROVED** [review]

**Comment by heath-freenome** [comment]
> @heath-freenome I can also update vite to use `build` as the dist folder like the rest of the packages: https://vitejs.dev/config/build-options.html#build-outdir
> 
> Let me know if you want me to do that

If this PR doesn't work then I will have you make those changes

**Comment by heath-freenome** [comment]
> > @heath-freenome I can also update vite to use `build` as the dist folder like the rest of the packages: https://vitejs.dev/config/build-options.html#build-outdir
> > Let me know if you want me to do that
> 
> If this PR doesn't work then I will have you make those changes

@ranihorev The build works, but the deploy of gh-pages is broken, thus the playground gives a 404

**Comment by ranihorev** [comment]
@heath-freenome I'm assuming that you mean before your fix in this PR, right?
Let me know if I can help

**Pull request merged**
