### PR TITLE
Fix local build errors from @types/json-schema

### PR DESCRIPTION
**Pull request by paintedbicycle**
Updates `@types/json-schema` dependency to latest in order to fix local build errors.

More details: https://github.com/rjsf-team/react-jsonschema-form/issues/2259#issuecomment-806309555

### CODE REVIEW

**Comment by epicfaace** [comment]
Thanks -- I think you need to update `package-lock.json` in order to fix CI.

Also, I'm curious why this didn't break CI earlier -- ideally, we'd be able to catch issues like this through CI. Any thoughts on how we can change CI to replicate your circumstances so it can fail on the `@types/json-schema` errors?

**Comment by paintedbicycle** [comment]
I'm happy to push up the lock files. I omitted them because I noticed they were huge diffs, so got concerned that maybe you weren't updating them on your end until a new release is cut or something like that. But I actually think the large lock file diffs part of the new npm 7 changes which introduced [`v2` of their lock file](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile). LMK if you'd prefer I downgrade to npm@6 or if it's ok to push npm@7 lock files.

I also wonder if this entire issue is around npm 7 changes which includes [peer dependency changes](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies)

Could be the answer to both my issue and also your CI stuff?

**Comment by paintedbicycle** [comment]
I downgraded to npm@6 for now and pushed the lockfiles. Hopefully that fixes the checks for this PR

**Comment by epicfaace** [comment]
Yes, thanks for adding npm v6 lock files. Ah, perhaps the issue is caused by npm v7, as I did notice that node 15 was failing on CI earlier. I'll try adding that build here.

**Comment by paintedbicycle** [comment]
@epicfaace Feels like the checks are stuck. Might have to kick it with another build

**Comment by epicfaace** [comment]
It looks like this PR still fails on Node 15, so I just removed it from CI for now.

I'm fine with merging this PR as-is -- the only drawback here is that we can't guarantee through CI that this kind of error won't happen again. On the other hand, if we are able to replicate this issue through CI and add a CI check for it, we can more reliably prevent it from regressing. Lmk if you have any thoughts on how else we could try replicating this on CI -- otherwise let's merge it.

**Review by epicfaace — APPROVED** [review]

**Comment by paintedbicycle** [comment]
@epicfaace Cool, let's merge. Thank you!

**Pull request merged**
