### PR TITLE
Drop support for node 8 / 9

### PR DESCRIPTION
**Pull request by epicfaace**
### Reasons for making this change

Node 8 / 9 are no longer supported, and some of our dependencies no longer support these versions at all (see #2030, #2014).

### CODE REVIEW

**Review by jimmycallin — CHANGES_REQUESTED** [review]
💯 💯 

But I think you also need to update the `engines` key value in the various package.json, and whatever it is that sets the required builds in the CI check.

**Review by stanlemon — APPROVED** [review]
Awesome! One thought, doesn't 10 end the maintenance window in April?

**Comment by epicfaace** [comment]
That's true, though I think we can wait a bit before actually dropping support for it.

**Comment by stanlemon** [comment]
> That's true, though I think we can wait a bit before actually dropping support for it.

Sure, I was just thinking in terms of v3 and breaking changes is all.

**Comment by epicfaace** [comment]
Yeah, that's a good point. I guess we might as well drop official support for it (though it will likely still work on Node 10, we can just remove it from CI).

**Comment by epicfaace** [comment]
Please take a look: https://github.com/rjsf-team/react-jsonschema-form/pull/2299

**Pull request merged**
