### PR TITLE
upgrade jsonpointer to 5.0.0 to address security vulnerability

### LINKED ISSUE #2598: jsonpointer vulnerability in 4.1; need to upgrade to 5.0
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
`@rjsf/core` currently depends on `"jsonpointer": "^4.0.1"`, which has a medium-severity security vulnerability according to https://snyk.io/test/npm/jsonpointer/4.1.0

jsonpointer v5.0 does not have this vulnerability: https://snyk.io/advisor/npm-package/jsonpointer

### Version
3.2.0

### PR DESCRIPTION
**Pull request by stevenhao**
closes #2598

### CODE REVIEW

**Comment by stevenhao** [comment]
Let me know if there's anything else i can do to drive this forward. My team is currently blocked from using rjsf due to this security flag.

**Review by epicfaace — COMMENTED** [review]
Looks good -- are there any breaking changes from jsonpointer 4 to 5 that we should be aware about before adding this in?

**Comment by epicfaace** [comment]
Also, thanks for your help here. If you're willing to, after this PR, would you be able to help add a CI check that would run `snyk test` to ensure we catch any future vulnerabilities?

**Comment by stevenhao** [comment]
Let me look into it!

**Comment by stevenhao** [comment]
Re breaking changes: I couldn't find a changelog (see https://github.com/janl/node-jsonpointer/pull/53). I believe it's backwards compatible though.

**Comment by epicfaace** [comment]
Got it, I looked through the code and found a changelog here -- https://github.com/janl/node-jsonpointer/pull/56 -- looks like it's just a security vulnerability fix.

**Review by epicfaace — APPROVED** [review]

**Pull request merged**
