### PR TITLE
#2439 bump core dep in package peer deps

### PR DESCRIPTION
**Pull request by wegry**
### Reasons for making this change

Re-add the ability to use @rjsf/core version within lerna.

If this is related to existing tickets, include links to them as well. Use the syntax `fixes #[issue number]` (ex: `fixes #123`).

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by jimmycallin — CHANGES_REQUESTED** [review]
Thanks! I believe you also should run `npm install` to update the package-lock.json file the new dependency requirements.

**Comment by epicfaace** [comment]
> Thanks! I believe you also should run `npm install` to update the package-lock.json file the new dependency requirements.

Actually, I don't think this is required. This is because peer dependencies won't be installed automatically when using node 14, so the package-lock.json files will be unchanged. In fact, we can see that that is the case because CI runs `npm ci`, which would have errored if the package-lock.json files are out of date.

**Review by epicfaace — APPROVED** [review]

**Review by jimmycallin — APPROVED** [review]

**Comment by jimmycallin** [comment]
> > Thanks! I believe you also should run `npm install` to update the package-lock.json file the new dependency requirements.
> 
> Actually, I don't think this is required. This is because peer dependencies won't be installed automatically when using node 14, so the package-lock.json files will be unchanged. In fact, we can see that that is the case because CI runs `npm ci`, which would have errored if the package-lock.json files are out of date.

ah, interesting, good to know and apologies for the wrong change request

**Comment by epicfaace** [comment]
No worries!

**Comment by kerematam** [comment]
https://github.com/rjsf-team/react-jsonschema-form/issues/2486#issuecomment-888314289

**Pull request merged**
