### PR TITLE
remove git-add command from lint-staged 

### PR DESCRIPTION
**Pull request by OlushesiToheeb**
### Reasons for making this change

[Please describe them here]

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by epicfaace — COMMENTED** [review]
Thanks -- can you revert the changes in the package-lock.json files? Then it should work.

**Comment by OlushesiToheeb** [comment]
> Thanks -- can you revert the changes in the package-lock.json files? Then it should work.

@epicfaace kindly elaborate more i dont think i understand you

**Comment by epicfaace** [comment]
You've changed a lot of package-lock.json files in this PR, see here:

image

Can you revert those changes?

**Comment by OlushesiToheeb** [comment]
> You've changed a lot of package-lock.json files in this PR, see here:
> 
> image
> 
> Can you revert those changes?

on here? I dont think i can kindly let me know how i can

**Comment by OlushesiToheeb** [comment]
I think can now @epicfaace

**Comment by epicfaace** [comment]
There are still a few package-lock.json files that you need to revert

**Comment by OlushesiToheeb** [comment]
@epicfaace have revert everything` package.lock.json` but is not still working

**Comment by epicfaace** [comment]
I think we're all good! The Netlify issue doesn't have to do with this PR; it was fixed on master.

**Review by epicfaace — APPROVED** [review]
Great work!

**Pull request merged**
