### PR TITLE
Remove undefined "name" parameter for material-ui

### PR DESCRIPTION
**Pull request by tisdadd**
### Reasons for making this change

Had issues merging in base changes with old pull request, so recreated the repo since very few files touched. This addresses lack of 'name' being there for static site generator.

### Checklist

* [ ] **I'm updating documentation**
  - [x ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by tisdadd** [comment]
@stanlemon This is the continuation of https://github.com/rjsf-team/react-jsonschema-form/pull/1817

**Comment by stanlemon** [comment]
Looks solid, thanks for redoing the PR!

I don't know what's up with the netlify stuff, maybe @epicfaace will have some insight there?

**Comment by epicfaace** [comment]
There appears to be a problem with netlify in general (with pipes not working in certain instructions). I contacted Netlify Support and they said they're working on it, so it doesn't have to do with this PR.

**Comment by epicfaace** [comment]
I don't think netlify is a required check -- we can just ignore it and merge this PR.

To fix the particular issue with netlify, though, they said a workaround is to move the "git log -1 --pretty=%an | grep dependabot[bot]" code to a .sh script file and then run that script file.

**Pull request merged**
