### PR TITLE
Help elements need a predictable ID

### PR DESCRIPTION
**Pull request by bradhugh**
### Reasons for making this change

When a ui:help is added to uiSchema for a property, the generated p or div tag needs to have an id attribute so it addressable.  This same thing already exists for description fields. This is needed for association with the corresponding form fields for accessibility (like adding aria-describedby="helpId") on the associated input fields.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### Deploy preview

Once CI finishes, you should be able to view a deploy preview of the playground from this PR at this link: https://deploy-preview-[PR_NUMBER]--rjsf.netlify.app/

### CODE REVIEW

**Review by epicfaace — COMMENTED** [review]
Thanks -- are there any similar changes that could / should be done for other themes' help elements as well?

**Comment by bradhugh** [comment]
> Thanks -- are there any similar changes that could / should be done for other themes' help elements as well?

It doesn't look like many of the templates actually override the Help field.  I don't know anything about semantic-ui, but take a look at HelpField.js in semantic-ui.  Right now it's got the following:
`<HelpField helpText={rawHelp} id={id} />`

I'll try to dig a bit and understand where it's getting "id" from in this context.

**Comment by bradhugh** [comment]
Yep, that's what I thought. It's actually duplicating the id here which is a bug. I'll make a change to fix this but while I'm here.

image

**Comment by bradhugh** [comment]
@epicfaace anything else I need to do here?

**Review by epicfaace — APPROVED** [review]
Thanks! This looks great.

**Review by epicfaace — COMMENTED** [review]
Actually, maybe we should add some snapshot tests for the themes with help fields? Just so we make sure that in the future, help fields always have ids that end with "__help" and this doesn't regress.

**Pull request merged**
