### PR TITLE
Utils.js - allow dependencies to use definitions

### PR DESCRIPTION
**Pull request by edparsons**
By adding definition to the validator definitions on the schema can be accessed inside dependency schemas.

### Reasons for making this change

At the moment if you try to reference definitions inside the oneOf part of a dependency it fails.

If this is related to existing tickets, include links to them as well.

### Checklist

* [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests

### CODE REVIEW

**Comment by epicfaace** [comment]
@edparsons thanks for the PR! Can you add a test that uses a schema that caused an error before this change?

**Comment by edparsons** [comment]
> @edparsons thanks for the PR! Can you add a test that uses a schema that caused an error before this change?

Hi @epicfaace I've added a test and without the fix the test fails with:
 1) utils
       retrieveSchema()
         schema dependencies
           conditional
             with $ref in oneOf
               should retrieve referenced properties from root schema definitions:
     Error: Could not find a definition for #/definitions/a.

**Comment by ed-workbase** [comment]
Hey checking in on this PR, looks like it's all good with a test and just needs an approval

**Comment by heath-freenome** [comment]
Closing this as we have removed `definitions` from the `@rjsf` version 5 release (see the `rjsf-v5` branch)

**Pull request closed without merging**
