### PR TITLE
typescript project references

### PR DESCRIPTION
**Pull request by zxbodya**
Adding configuration for typescript project references

As part of it also splitted snapTests from core to separate package - this is to avoid imports for code not included in package exports, and also will allow themes developed outside oof this monorepo to depend on it.

### Reasons for making this change

- improve typescript build times
- including test files in type-check

depends on #3781

### CODE REVIEW

**Comment by heath-freenome** [comment]
@zxbodya Will you have a chance to update and resolve the conflicts in this PR?

**Comment by heath-freenome** [comment]
@zxbodya Let's get this merged into `5.14.0` as soon as you rebase and deal with the conflicts. Sorry it has taken so long

**Review by nickgros — APPROVED** [review]
I believe we reviewed this a while ago and decided it was ready. Thanks @zxbodya !!

**Comment by heath-freenome** [comment]
@zxbodya Ok, the new fluent-rc theme is merged, please rebase, update and ready your PR for merge ASAP. I hope to cut a new release by monday

**Review by heath-freenome — COMMENTED** [review]
@zxbodya A couple of small tweaks and then I'll merge and build a new release

**Pull request merged**
