### PR TITLE
experimental_customMergeAllOf

### PR DESCRIPTION
**Pull request by MarekBodingerBA**
### Reasons for making this change

**NOTE: This is just a draft PR; details are subject to discussion.**

In many cases, [json-schema-merge-allof](https://github.com/mokkabonna/json-schema-merge-allof) is a performance bottleneck for this library:
- There are a few related issues: https://github.com/rjsf-team/react-jsonschema-form/issues/2811. https://github.com/rjsf-team/react-jsonschema-form/issues/3258 (this change allows to use custom keywords for the original library).
- The library is unmaintained, with the last [release](https://www.npmjs.com/package/json-schema-merge-allof?activeTab=versions) on 22/01/2021 (4 years ago).
- The library [deep clones](https://github.com/mokkabonna/json-schema-merge-allof/blob/ea2e48ee34415022de5a50c236eb4793a943ad11/src/index.js#L312) every schema, and this cloning is called recursively for each call. In large production schemas, this is detrimental to performance.
- There are "new players on the block" such as [allof-merge](https://github.com/udamir/allof-merge) that [promise](https://github.com/udamir/allof-merge/tree/master?tab=readme-ov-file#benchmark) much better performance. 
- For our use case, as we only use limited features of JSON Schema, we can use a very fast [custom implementation](https://gist.github.com/MarekBodingerBA/5bb3aeda02d2255c7e1d023eac22168c) of merging. This largely solves the library's performance issues for us; `getDefaultFormState` (not just the merging itself) performs 7x faster in our implementation:
```
getDefaultFormState_original x 141 ops/sec ±2.65% (80 runs sampled)
getDefaultFormState_fastMergeAllOf x 987 ops/sec ±2.72% (77 runs sampled)
```

I have a couple of questions:
- Is this something that would be desirable to implement for others?
- I would like feedback on the naming and types of `experimental_customMergeAllOf`. Maybe it's better to provide the function wrapped in an object rather than the function itself.
- `schemaParser` (which is only used in `compileSchemaValidatorsCode`) relies internally on `retrieveSchemaInternal`. I chose not to add this option here; is it necessary to include it?

The functional change is located [here](https://github.com/rjsf-team/react-jsonschema-form/pull/4308/files#diff-03661af48370908512b3758c30bf0d7fb27a1bca19e5de5442f8ec9332c0e37aR476), other changes are just adding the argument where needed.

### Checklist

- [x] **I'm updating documentation**
  - [x] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [x] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by MarekBodingerBA** [comment]
When I think about it, I would implement it now as an object (that would be easier for future compatibility). I imagine something like this:
```
export type Experimental_MergeAllOfOptions<S extends StrictRJSFSchema = RJSFSchema> =
  | {
      merger: "default";
      overideOptions: Options; // json-schema-merge-allof options
    }
  | {
      merger: "custom";
      mergeFn: (schema: S) => S;
    }
  | {
      merger: "xyz"; // other library if added in the future
    };
```

WDYT?

**Comment by heath-freenome** [comment]
@MarekBodinger I totally understand why you want to add this. We feel like exposing the `Options` for `json-schema-merge-allof` is a bad idea. Honestly, if [allof-merge](https://github.com/udamir/allof-merge) has better performance and doesn't break our exists tests, then we welcome a PR to swap it in. That said, making it an object just to provide a function seems like overkill. So making it be a merge function like you started is fine. Not sure whether we can/want to expose this in the playground.

**Comment by nickgros** [comment]
Also linking this bug: https://github.com/rjsf-team/react-jsonschema-form/issues/2927 which may be fixed by an alternative/improved merge implementation

**Comment by nickgros** [comment]
I tried to just plug in `allof-merge` and the only meaningful test failure was [this one in retrieveSchemaTest](https://github.com/rjsf-team/react-jsonschema-form/blob/4cb834266187d95a0421292c7bdb7746466a9d8c/packages/utils/test/schema/retrieveSchemaTest.ts#L940). It looks like `allof-merge` has a lot of customization options, so it may be worth spending a bit of time to see if the behavior can be tweaked to get it to work properly, and we could make it the default implementation (if you're interested in looking into it @MarekBodingerBA)

**Comment by MarekBodingerBA** [comment]
I don't think it is a good to replace j`son-schema-merge-allof` with `allof-merge` without thorough testing. As a user of this library, I would be concerned about such a change.

The approach already in progress, which introduces an `experimental_customMergeAllOf` option, is more appropriate. This would allow interested users who understand the implications to provide their own custom implementation, where they could easily incorporate `allof-merge` if desired.

I've completed the work on this and appreciate the feedback received.

**Review by nickgros — APPROVED** [review]
LGTM!

**Comment by nickgros** [comment]
@MarekBodingerBA can you resolve the conflicts? Likely because we merged #4312

**Comment by MarekBodingerBA** [comment]
@nickgros Unfortunately, I don't have access to a computer for next three weeks. Is it something that you are able to do, or should we wait until I come back?

**Comment by nickgros** [comment]
@MarekBodingerBA I don't have permission to update your branch. Could you give me permission (I think in this PR you can give me permission to modify only this branch). Otherwise I could either create a new PR or wait for you to have time. Up to you!

**Comment by MarekBodingerBA** [comment]
@nickgros I resolved the conflicts.

**Pull request merged**
