### PR TITLE
Allow choosing a seperate widget for MultiSelect rather than just Select

### PR DESCRIPTION
**Pull request by bockelie93**
### Reasons for making this change

Allows you to override just the MultiSelectWidget without overriding SelectWidget. Use-case is that you would like to render all your multi-choice arrays as checkboxes rather than a multiselect without having to provide an UiSchema for each of your values.

i.e. 
const widgets = { MultiSelectWidget: CheckBoxesWidget };

Fixes https://github.com/mozilla-services/react-jsonschema-form/issues/1193

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [X] **I'm adding or updating code**
  - [X] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [X] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
Thanks for the PR -- however, this is backwards-incompatible (imagine if there has already been code utilizing SelectWidget for array widget customization). Perhaps it can check if MultiSelectWidget is defined, and otherwise use SelectWidget?

**Comment by bockelie93** [comment]
Sorry about that.

Now it should check if the MultiSelectWidget property is defined in widgets, otherwise use the SelectWidget. Maybe naming could be worked on, as it doesn't really make sense to overwrite the MultiSelectWidget with say CheckboxesWidget. 

I also added two more tests related to MultiSelect, as SelectWidget (without MultiSelectWidget being defined) and MultiSelectWidget should have the same behaviour.

**Comment by bockelie93** [comment]
Any ETA on this? @epicfaace

**Comment by epicfaace** [comment]
@bockelie93 thanks for the reminder. It looks good -- can you please update documentation to include the multiselectwidget and also the behavior for MultiSelectWidget -> SelectWidget?

**Comment by bockelie93** [comment]
Sure, I'll try to make room for it after work.

**Comment by limjiayi** [comment]
Any updates on this? I have a great use case for this functionality and this PR is nearly ready to merge.

**Comment by bockelie93** [comment]
Sorry about that. We ended up scrapping the package in our project, so I kind of forgot about. 

Looks like there's only documenation missing. I can try to squeeze in some time over weekend for it, but feel free to do it if I fail to deliver over the weekend.

**Comment by Morriz** [comment]
would love to see this...

**Pull request closed without merging**
