### PR TITLE
fix(@rjsf/core): custom field that is any of displays twice

### PR DESCRIPTION
**Pull request by truh**
### Reasons for making this change

If a custom field is provided for an anyOf schema, it should be rendered in place of the `AnyOfField` component rather than be wrapped in the `AnyOfField` component. Same for oneOf.

https://github.com/rjsf-team/react-jsonschema-form/issues/2691

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [x] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
@truh Please add a test case that verifies this fix

**Comment by truh** [comment]
@heath-freenome do you know what's wrong?

The import

```
@rjsf/playground: Module not found: Error: Can't resolve '@rjsf/core/lib/components/fields/ObjectField' in '/home/runner/work/react-jsonschema-form/react-jsonschema-form/packages/playground/src/samples'
```

Looks fine imho and I don't get this error locally when I run

```
npm install
npm run build
npm start
```

Am I not allowed to import fields for the samples? I thought to do that to keep the sample code brief.

**Comment by heath-freenome** [comment]
> @heath-freenome do you know what's wrong?
> 
> The import
> 
> ```
> @rjsf/playground: Module not found: Error: Can't resolve '@rjsf/core/lib/components/fields/ObjectField' in '/home/runner/work/react-jsonschema-form/react-jsonschema-form/packages/playground/src/samples'
> ```
> 
> Looks fine imho and I don't get this error locally when I run
> 
> ```
> npm install
> npm run build
> npm start
> ```
> 
> Am I not allowed to import fields for the samples? I thought to do that to keep the sample code brief.

I am not sure. Your sample seems to be the only one that attempts to import something that is not explicitly exported from `@rjsf/core`'s index file. @epicfaace Do you have any ideas?

**Comment by heath-freenome** [comment]
Ah, when you are running locally the `@rjsf/core` is a symbolic link. Can you provide an example that doesn't use `ObjectField`?

**Comment by truh** [comment]
> Can you provide an example that doesn't use `ObjectField`?

sure

**Comment by truh** [comment]
@heath-freenome updated the example not to import ObjectField

**Comment by truh** [comment]
@heath-freenome this should fix the linting problems

**Comment by heath-freenome** [comment]
Would you be willing to rebase this on-top-of the upcoming beta branch -> `rjsf-v5`? That way it can be part of the next release

**Comment by truh** [comment]
@heath-freenome sure

**Comment by truh** [comment]
I'm done with the rebase. Unfortunately neither this branch nor the base branch rjsf-v5 would start on my machine.

@heath-freenome

**Comment by heath-freenome** [comment]
@truh Can you run `npm run cs-format` on the PR so that the build will pass?

**Comment by truh** [comment]
@heath-freenome done

**Review by heath-freenome — APPROVED** [review]

**Comment by heath-freenome** [comment]
@truh Approved, merge away

**Comment by heath-freenome** [comment]
@truh So I'm debugging why something in my implementation stopped being rendered and it turns out it is related to this PR. I need to allow the oneOf/anyOf to actually be rendered in conjunction with MY custom field. I'm leaning towards pushing a PR that changes this behavior to allow either an opt-out of showing the oneOf/anyOf behavior or an opt-in... Thoughts?

**Comment by truh** [comment]
Sounds alright. Thanks for the heads-up. @heath-freenome

**Pull request merged**
