### PR TITLE
Enable displaying descriptions for string, number fields in antd theme

### LINKED ISSUE #2033: Property descriptions not showing with antd
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Property descriptions on JSON Schema are not being shown with antd, but they are shown with every other theme.

### Steps to Reproduce

[Reproduction on playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpcnN0TmFtZSIsImxhc3ROYW1lIl0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJkZWZhdWx0IjoiQ2h1Y2siLCJkZXNjcmlwdGlvbiI6IkZpcnN0IG5hbWUgZGVzY3JpcHRpb24ifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIiwiZGVzY3JpcHRpb24iOiJMYXN0IG5hbWUgZGVzY3JpcHRpb24ifSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImFudGQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

Changing the theme will display a description for the fields "first name" and "last name".

#### Expected behavior

Description should be displayed following [antd specs](https://ant.design/docs/spec/data-entry#Tips-and-helps).

#### Actual behavior

Descriptions are not shown when theme antd is used.

### Version

Bug exists at least on the last release (2.3.0) and on master branch.

### PR DESCRIPTION
**Pull request by jakob-ed**
### Reasons for making this change

Descriptions were previously not shown in the antd theme for input fields of types string and number. Closes #2033.

#### Before

[Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhTmVzdGVkT2JqZWN0Ijp7fSwiZmlyc3ROYW1lIjoiQ2h1Y2siLCJsYXN0TmFtZSI6Ik5vcnJpcyIsImFnZSI6NzUsImJpbyI6IlJvdW5kaG91c2Uga2lja2luZyBhc3NlcyBzaW5jZSAxOTQwIiwicGFzc3dvcmQiOiJub25lZWQifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6ImFuT2JqZWN0IiwiZGVzY3JpcHRpb24iOiJhbk9iamVjdCBkZXNjcmlwdGlvbiIsInByb3BlcnRpZXMiOnsiYVN0cmluZyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJhU3RyaW5nIiwiZGVzY3JpcHRpb24iOiJhU3RyaW5nIGRlc2NyaXB0aW9uIn0sImFOdW1iZXIiOnsidHlwZSI6Im51bWJlciIsInRpdGxlIjoiYU51bWJlciIsImRlc2NyaXB0aW9uIjoiYU51bWJlciBkZXNjcmlwdGlvbiJ9LCJhTmVzdGVkT2JqZWN0Ijp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6ImFOZXN0ZWRPYmplY3QiLCJkZXNjcmlwdGlvbiI6ImFOZXN0ZWRPYmplY3QgZGVzY3JpcHRpb24ifSwiYU5lc3RlZEFycmF5Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiYU5lc3RlZEFycmF5IiwiZGVzY3JpcHRpb24iOiJhTmVzdGVkQXJyYXkgZGVzY3JpcHRpb24iLCJpdGVtcyI6e319fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImFudGQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

image

##### After

image

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by stewartmcgown — APPROVED** [review]
Concise!

**Comment by foucdeg** [comment]
Hello, this looks close to done, is it coming anytime soon?

**Comment by Maikel-Nait** [comment]
I'm also in need of this.  Any possibility of having it merged or updated to pass ?

**Comment by jakob-ed** [comment]
From my side, it's ready to be merged but I can't get the CI to pass and didn't succeed in adapting the tests to this change. @epicfaace could you maybe take a look and give me some hints? 

In the meantime, I created a custom `FieldTemplate` as a workaround. I copied packages/antd/src/templates/FieldTemplate/index.js to a file in my project FieldTemplateWithDescription.js, changed the import of `WrapIfAdditional` to be absolute and changed the one line to enable descriptions:

**FieldTemplateWithDescription.js**
```jsx
import React from 'react';

import Form from 'antd/lib/form';

import WrapIfAdditional from '@rjsf/antd/dist/es/templates/FieldTemplate/WrapIfAdditional';

const VERTICAL_LABEL_COL = { span: 24 };
const VERTICAL_WRAPPER_COL = { span: 24 };

const FieldTemplate = ({
  children,
  classNames,
  description,
  disabled,
  displayLabel,
  // errors,
  // fields,
  formContext,
  help,
  hidden,
  id,
  label,
  onDropPropertyClick,
  onKeyChange,
  rawDescription,
  rawErrors,
  rawHelp,
  readonly,
  required,
  schema,
  // uiSchema,
}) => {
  const {
    colon,
    labelCol = VERTICAL_LABEL_COL,
    wrapperCol = VERTICAL_WRAPPER_COL,
    wrapperStyle,
  } = formContext;

  if (hidden) {
    return <div className="field-hidden">{children}</div>;
  }

  const renderFieldErrors = () =>
    [...new Set(rawErrors)].map((error) => (
      <div key={`field-${id}-error-${error}`}>{error}</div>
    ));

  return (
    <WrapIfAdditional
      classNames={classNames}
      disabled={disabled}
      formContext={formContext}
      id={id}
      label={label}
      onDropPropertyClick={onDropPropertyClick}
      onKeyChange={onKeyChange}
      readonly={readonly}
      required={required}
      schema={schema}
    >
      {id === 'root' ? (
        children
      ) : (
        <Form.Item
          colon={colon}
          extra={displayLabel && rawDescription && description}
          hasFeedback={schema.type !== 'array' && schema.type !== 'object'}
          help={(!!rawHelp && help) || (!!rawErrors && renderFieldErrors())}
          htmlFor={id}
          label={displayLabel && label}
          labelCol={labelCol}
          required={required}
          style={wrapperStyle}
          validateStatus={rawErrors ? 'error' : undefined}
          wrapperCol={wrapperCol}
        >
          {children}
        </Form.Item>
      )}
    </WrapIfAdditional>
  );
};

export default FieldTemplate;
```

Then you can use it like `<Form FieldTemplate={FieldTemplateWithDescription} />` in your code. Hope this helps.

**Comment by jakob-ed** [comment]
Fixed in https://github.com/rjsf-team/react-jsonschema-form/pull/2644

**Pull request closed without merging**
