### PR TITLE
Lausselloic fix readonly on select element for Bootstrap 4 theme

### LINKED ISSUE #2616: [Theme][Bootstrap4] Readonly attribute is not valid on select element
Hello,

Looks like there's a mistake on bootstrap4 select Widget that have been fixed in core. Readonly attribute have no effect on select element. So maybe like in core https://github.com/rjsf-team/react-jsonschema-form/blob/79a61ff70c25f84ec3e989899ac7f92d1dd3e443/packages/core/src/components/widgets/SelectWidget.js#L74 use disabled on select element if readonly or disabled value is set to true?

https://github.com/rjsf-team/react-jsonschema-form/blob/79a61ff70c25f84ec3e989899ac7f92d1dd3e443/packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx#L91

### PR DESCRIPTION
**Pull request by Lausselloic**
### Reasons for making this change
Just remove the readonly attribute and use disabled one for both readonly and disabled option onto select element
fixes #2616

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [ ] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
Thank you! Can you please add some snapshot tests that test this functionality for both themes?

**Comment by Lausselloic** [comment]
I'll try to fix existing snapshot errors, don't know if I will have time to add more tests

**Comment by Lausselloic** [comment]
Hello, I've added 2 more test for bootstrap4 template to check that readOnly attribute define the disabled one on select element. I've remove my changes on semanticUI as I'm not expert on semanticUI, and the template generate fake HTML form element (div in fact) so I don't know how to manage it. On playground tests with semanticUI show that readonly/disabled satet doesn't affect all elements. I don't know if there's user of that theme

**Comment by Lausselloic** [comment]
hello @epicfaace do I need to do more on this PR? I've remove code for semanticUI as I'm not able to fix it. But I think that for Bootstrap it's okay.

Let me know

**Comment by epicfaace** [comment]
I still need to look into this, thanks for the reminder!

--
Ashwin Ramaswami

**Comment by heath-freenome** [comment]
This was reimplemented in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3036

**Pull request closed without merging**
