### PR TITLE
Allow for ui option to hide label on text widgets if passed

### PR DESCRIPTION
**Pull request by devo-wm**
### Reasons for making this change

Passing `{"ui:label": false}` nor  `{"ui:options": {label: false}` to the uiSchema only hides the help text in the bs4 theme.

Partial fix for #1998 
### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### Deploy preview

Once CI finishes, you should be able to view a deploy preview of the playground from this PR at this link: https://deploy-preview-[PR_NUMBER]--rjsf.netlify.app/

### CODE REVIEW

**Review by epicfaace — COMMENTED** [review]
Thanks! Can you remove the comment and also add a test?

**Comment by newt10** [comment]
@epicfaace, #2533 also fixes this, I am going to close this as a duplicate since the problem is addressed by #2533 .

**Comment by newt10** [comment]
@devo-wm , Can you test using #2533  and confirm that the problem is fixed, if there are any other issues, please feel free to re-open or raise a new one. Thanks

**Comment by epicfaace** [comment]
(@newt10 the usual workflow is to close the issue only once the PR is merged)

**Pull request closed without merging**
