### PR TITLE
Playground React 18

### PR DESCRIPTION
**Pull request by ahkhanjani**
### Reasons for making this change

This is a step to move the Playground to Next.js

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [x] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
@ahkhanjani Have you run the playground with this? I want to make sure it works properly

**Review by heath-freenome — APPROVED** [review]

**Review by heath-freenome — CHANGES_REQUESTED** [review]
Can you add a description of this change into the `CHANGELOG.md`?

**Comment by heath-freenome** [comment]
Also, have you any plans to deal with the react 18 warnings in the other packages?

**Comment by ahkhanjani** [comment]
> Have you run the playground with this? I want to make sure it works properly

I finally figured the npm changing my package locks issue but my `npm run build`s are still failing.
I've yet to switch to React 18 API. The next commit should actually make React 18 take over. There are no other client side breaking changes and it should work just fine in theory. If you're willing to test you have access to my repo.

> Also, have you any plans to deal with the react 18 warnings in the other packages?

Yes. Although I need to check the compatibility of all the UI libraries with it first which will have to wait after I'm finished with this.

@heath-freenome I'm planning to move the docs to Astro. Is that OK with you?

**Comment by heath-freenome** [comment]
> > Have you run the playground with this? I want to make sure it works properly
> 
> I finally figured the npm changing my package locks issue but my `npm run build`s are still failing. I've yet to switch to React 18 API. The next commit should actually make React 18 take over. There are no other client side breaking changes and it should work just fine in theory.

Given how many more big changes you are planning, I'd really love to:

1. Have you start attending the Friday meeting so we can talk about and coordinate changes
2. Get your local build working so that I am not needing to personally validate all of your work

> If you're willing to test you have access to my repo.

I did try it out and it SEEMS to work ok, minus the react 18 warnings... which seem to indicate you forgot to do at least one thing in this PR. But maybe you DO want to wait for this last change until after you get react 18 fully working.

Screenshot 2023-04-10 at 5 12 13 PM

> 
> > Also, have you any plans to deal with the react 18 warnings in the other packages?
> 
> Yes. Although I need to check the compatibility of all the UI libraries with it first which will have to wait after I'm finished with this.
> 
> @heath-freenome I'm planning to move the docs to Astro. Is that OK with you?

We literally JUST switched to docusaurus. What is reason for switching to `Astro`? If you can make it to the Friday meeting to talk about it, I'd love to go over it.

**Comment by ahkhanjani** [comment]
> 1. Have you start attending the Friday meeting so we can talk about and coordinate changes

This sounds fair right now. I'll do whatever I can to be present this Friday.

> 2. Get your local build working so that I am not needing to personally validate all of your work

After I switched to PNPM my build succeeded first try. There is something wrong with NPM or some code in this repo that makes my builds fail. I've tried clean cloning and installing everything from scratch but every time something failed. I tried Node latest out of the box NPM and NPM latest versions both and it didn't make a difference. It's odd that PNPM finished building successfully. I guess I can try finishing the [PNPM PR](#3592) first. Sorry for the inconvenience. But still as a normal outsider of this project it's worth investigating the reason why something like this would fail.

> I did try it out and it SEEMS to work ok, minus the react 18 warnings...

The first warning shouldn't be there after my last commits. Did you try the latest build? I'll work on it

> We literally JUST switched to docusaurus. What is reason for switching to `Astro`? If you can make it to the Friday meeting to talk about it, I'd love to go over it.

We can discuss it in the meeting

**Comment by ahkhanjani** [comment]
@heath-freenome I've realized the build process does not perform type checking. Is this intentional? I'm seeing type errors in my IDE after building projects

**Comment by heath-freenome** [comment]
> @heath-freenome I've realized the build process does not perform type checking. Is this intentional? I'm seeing type errors in my IDE after building projects

That's a little surprising since I thought DTS did type checking as part of its process. We could try adding a type check step in the build.

**Comment by heath-freenome** [comment]
@ahkhanjani How can we make it easier for you to attend the Friday meeting?

**Comment by ahkhanjani** [comment]
> How can we make it easier for you to attend the Friday meeting?

@heath-freenome Hi. Sorry for being absent all of a sudden. I actually joined the discord server a few weeks ago to attend the meeting; I just have to work over time at my job for the deadline. I will join you and make these work right after

**Comment by heath-freenome** [comment]
@ahkhanjani I'm guessing work is still keeping you very busy?

**Comment by ahkhanjani** [comment]
@heath-freenome Yes actually a lot. Based on your frequency of checking on my work progress I assume I'm blocking something? If that's the case you should ignore my PRs for the time being. If you have to upgrade to React 18 immediately I suggest you do it on your own as I'm probably busy for another month and fixing my issue with npm seems unlikely at the moment. Best regards

**Pull request closed without merging**
