### PR TITLE
$data passed into AJV instance

### PR DESCRIPTION
**Pull request by zeddotes**
### Reasons for making this change
`$data: true` wasn't previously passed to the internal AJV instance that's created for validation so it wasn't previously possible to have conditional validations in a standard way as specified the by the 07 Json schema draft.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
Hey, thanks for the PR. It seems like `$data` never made it into the AJV spec (see https://github.com/json-schema-org/json-schema-spec/issues/51) -- do you have a specific part of the spec in mind that mentions this when you refer to what is "specified by the 07 Json schema draft"?

**Comment by zeddotes** [comment]
Hey @epicfaace! Sorry for the confusion, I was looking at https://json-schema.org/draft/2019-09/relative-json-pointer.html and figured that it was a feature that had been supported by the draft. The main purpose of the PR is more to enable the JSON-pointer functionality for the library than it is to stay up to date with what's in the JSON Schema spec.

`$data` seems like it is (as much as I've experimented with it) a very helpful feature by AJV as it allows for validations based on internal data for conditional validations against the provided schema.

**Comment by calpa** [comment]
I find that I all I need is to parse `$data: true` to `new Ajv`, but currently the ajv options are hard coded...

**Comment by calpa** [comment]
If the PR is not merged and someone need to pass the `$data` option to Ajv contrutor, just copy the validate.js and change import paths.

**Comment by katosad** [comment]
Are there any plans to merge this PR? Would be a helpful feature for our team's use case.

**Comment by heath-freenome** [comment]
Closing this because in the upcoming @rjsf v5 release we refactored the ajv 6 validator into its own package `@rjsf/validator-ajv6`. This package allows you to create your validator with custom ajv options, such as `$data` thereby giving you more control over how it functions. For more information see PR #2929

**Pull request closed without merging**
