### PR TITLE
Add null checks for ArrayField

### PR DESCRIPTION
**Pull request by gavin-haynes-grow**
### Reasons for making this change

When an array is set to "null" instead of empty, the page crashes instead of specifying an error or allowing it to be null.

Related to https://github.com/rjsf-team/react-jsonschema-form/issues/1346 but that may be a separate issue.

This change fixes the issue you can see at https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyZXF1ZXN0IjpudWxsfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InJlcXVlc3QiOnsidHlwZSI6WyJhcnJheSIsIm51bGwiXSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyJ9fX19LCJ1aVNjaGVtYSI6e319, where nothing is displayed because the component crashes.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests (not sure if this can be tested with the current test framework. I tried a simple test using setProps but it didn't fail on the previous commit)
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
@gavin-haynes-grow you could base your test off of a similar test, like https://github.com/rjsf-team/react-jsonschema-form/blob/ef8b7fce19c5271f75a849fa951ad62595314b00/packages/core/test/ArrayField_test.js#L1155

**Comment by richmahn** [comment]
Where are we on this? We really need arrays to also allow "null".

**Comment by epicfaace** [comment]
@richmahn we just need a test and need to update this PR to master. Would you be able to help with that?

**Comment by richmahn** [comment]
@epicfaace Sure, I can help with that. Trying this out now.

**Comment by epicfaace** [comment]
@richmahn @mowses anyone want to finish up this PR? It's nearly done -- just needs a test.

**Comment by richmahn** [comment]
@gavin-haynes-grow Has conflicts. Can you add me to your fork as a collaborator and I'll resolve conflicts and write a test?

**Comment by epicfaace** [comment]
@richmahn you could also just add these changes to your own fork, then make a new PR.

**Comment by richmahn** [comment]
@epicfaace Ok, thought about doing that and probably in May did start my own fork

**Comment by richmahn** [comment]
@epicfaace Ok, opened a new PR here: https://github.com/rjsf-team/react-jsonschema-form/pull/1992. Looking to see what tests can be made.

**Comment by richmahn** [comment]
@epicfaace Needing to make a snapshot for my test. I'm used to using jest, but since this uses TypeScript, running just "jest -u" causes all tests to fail. Running `npm test -u` or `nmp test -- -u` doesn't work, saying that lerna doesn't have that argument. Any ideas?

**Comment by epicfaace** [comment]
@richmahn try doing `cd packages/core` and then run `npm test -- -u`.

**Comment by jsani-radar** [comment]
wanted to bump this PR, commented on the original issue: https://github.com/rjsf-team/react-jsonschema-form/issues/1346#issuecomment-769439171

**Comment by epicfaace** [comment]
Closing this PR in favor of #1992.

**Pull request closed without merging**
