### PR TITLE
Rename some props to be lowercase

### PR DESCRIPTION
**Pull request by ttbarnes**
### Reasons for making this change

I noticed that a few props start with uppercase and this bothered me. EG you can end up with:

```
<Form
  schema={}
  onChange={}
  onSubmit={}
  onError={}
  ErrorList={}
  FieldTemplate={}
  ObjectFieldTemplate={}
  ArrayFieldTemplate={}
/>
```

I've renamed these 4 props since I think it's cleaner/more consistent.
```
ErrorList           === errorList
FieldTemplate       === fieldTemplate
ObjectFieldTemplate === objectFieldTemplate
ArrayFieldTemplate  === arrayFieldTemplate
```

### Checklist

* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated docs if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style

### CODE REVIEW

**Comment by edi9999** [comment]
Since this is a breaking change (the public API changes in a non-retro compatible way), we should postpone this to a new release (2.0)

**Comment by glasserc** [comment]
I don't really agree with this change. These props are uppercase because they are the names of components. In JSX, `<foo>` is generally understood to be an HTML tag, and `<Foo>` is generally understood to be a component.

**Comment by edi9999** [comment]
I understand your point. I'm not sure if the convention applies only to tagnames, or also to props.

For example, the `props.children` is lowercase and not `props.Children`

**Comment by MatejMazur** [comment]
I think that if we find a way to merge #1013 then we don't need to bother with this because templates are moved under the `Form.props.templates`.

**Comment by epicfaace** [comment]
Closing this due to inactivity. I agree with @glasserc 's justification for not doing this change.

**Pull request closed without merging**
