### PR TITLE
Issue templates

### PR DESCRIPTION
**Pull request by jacqueswho**
### Reasons for making this change

- Updated the issue template to separate a bug from a feature request
- both templates have a section to select theme and add version
- both templates will have a default label [bug, needs triage] or [feature, needs triage]
- there are default assignees epicfaace,jacqueswho,heath-freenome . 
- The assignees will be decide the appropriate labels to apply and if needs to be assigned

[click new issue](https://github.com/jacqueswho/testing-templates/issues) for demo

### Checklist
I've added
* [x] **I'm adding or updating code**
description of the PR
* [x] **I'm adding a new feature**

### CODE REVIEW

**Comment by jacqueswho** [comment]
> Should we go ahead and remove this file (https://github.com/rjsf-team/react-jsonschema-form/blob/master/ISSUE_TEMPLATE.md) too then?

yes

**Comment by jacqueswho** [comment]
> Should we go ahead and remove this file (https://github.com/rjsf-team/react-jsonschema-form/blob/master/ISSUE_TEMPLATE.md) too then?

are you going to remove it?

**Comment by jacqueswho** [comment]
after this is approved and merged. delete the old https://github.com/rjsf-team/react-jsonschema-form/blob/master/ISSUE_TEMPLATE.md)

**Comment by epicfaace** [comment]
> after this is approved and merged. delete the old https://github.com/rjsf-team/react-jsonschema-form/blob/master/ISSUE_TEMPLATE.md)

Can you just do that in this PR?

**Comment by jacqueswho** [comment]
@epicfaace can this be approved?

**Comment by jacqueswho** [comment]
@epicfaace is there something I must do?

**Comment by jacqueswho** [comment]
@heath-freenome can you approve?

**Review by heath-freenome — APPROVED** [review]
Why is node 12 failing?!

**Pull request merged**
