### PR TITLE
semantic-ui: add submit button, email, url, date widgets

### PR DESCRIPTION
**Pull request by jacqueswho**
### Reasons for making this change

Features:

- added submitButton
- added Date and DateTime Widgets
- added email Widget
- added URLWidget

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [x] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by ErQrYfkrju** [comment]
@epicfaace @agustin107 ping

**Comment by ErQrYfkrju** [comment]
Hello @agustin107 @epicfaace @jacqueswho any news on this pull request?

**Comment by jacqueswho** [comment]
> Hello @agustin107 @epicfaace @jacqueswho any news on this pull request?


sorry @ErQrYfkrju cant do anything. just waiting.

**Comment by jacqueswho** [comment]
@epicfaace please can this be merged

**Review by epicfaace — APPROVED** [review]
Looks good to me. Apologies for the delay!

**Pull request merged**
