### PR TITLE
Implement bootstrap5 theme

### LINKED ISSUE #2428: Add Bootstrap 5 theme
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

`react-bootstrap` is in an early beta to support `bootstrap@5`. Copying the existing bootstrap 4 package seems like it would be a good way to start the move over. CSS classes are probably the biggest hurdle.

### PR DESCRIPTION
**Pull request by nurikk**
### Implement bootstrap5 theme

This PR adds support for bootstrap5 theme. It 99.99% copy of bootstrap4 theme, but has following differences:
1) This package depends on react-boostrap [v2](https://react-bootstrap.github.io/migrating/) (which enables support for bootstrap5) instead of `v1`
2) This package depends on updated `react-icons`
3) This package has slight changes in SelectWidget, to support react-boostrap v2

Resolves #2428

### Checklist

* [ ] **I'm updating documentation**
  - [x] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [x] **I'm adding a new feature**
  - [x] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
@nurikk Have you considered making this theme use the `@rjsf/bootstrap-4` and simply override `SelectWidget` in the `widgets`... something like:
``` Theme.tsx
import { Theme } from '@rjsf/bootstrap-4';
import SelectWidget from `../src/SelectWidget`;

const Theme5: WithThemeProps = {
  ...Theme,
  widgets: { ...Theme.widgets, SelectWidget }
}

export Theme;
```

You might keep all of the tests but you won't need most of the source files.

**Comment by jochenschmich-aeberle** [comment]
Hi there, just asking for an indication, whether this pull request is going to be merged?

**Comment by heath-freenome** [comment]
@jochenschmich-aeberle This PR will likely never be merged as it was made against a now very out-of-date v4 codebase. We are keeping it around as we are considering dropping support for bootstrap-4 in favor of bootstrap-5 when we officially support React 18 as part of the future v6 release. In the meantime, I believe that using the bootstrap-4 theme with bootstrap-5 is possible, assuming you fix the SelectWidget

**Comment by johan-smits** [comment]
Is there a tracking issue for BS5 implementation?

**Comment by heath-freenome** [comment]
@nurikk We are doing this in v6 with #3974

**Pull request closed without merging**
