### PR TITLE
Add errorSchema to onError prop callback.

### PR DESCRIPTION
**Pull request by theengineear**
Any qualms about exposing the `errorSchema` structure to a wrapping component in the `onError` method?

### Reasons for making this change

I'm using CSS-in-JS and looking to access the structured information in errorSchema. The flat structure of the errors array (currently passed back in `onError`) is good for printing out errors, but the names are missing then nested structure of the `errorSchema`.

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated docs if needed
  - [ ] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

^^ Before I do these things, I'm hoping to get an initial 👍 / 👎

### CODE REVIEW

**Comment by n1k0** [comment]
Sure, we should document this though.

**Comment by n1k0** [comment]
> Sure, we should document this though.

@theengineear Could you please take care of this? Thanks a lot.

**Comment by epicfaace** [comment]
@theengineear it's been a while -- do you still need this feature?

**Comment by theengineear** [comment]
@epicfaace , sorry for never getting back to document this. No I no longer need this. I think the use case is still valid. But we should close so that we don't add baggage to the codebase unnecessarily.

**Pull request closed without merging**
