### PR TITLE
Feature/ pass an object of Array field templates to form

### LINKED ISSUE #1680: Allow JSON registration of custom ArrayTemplateField and ObjectTemplateField
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Currently custom ArrayTemplateField and ObjectTemplateField components must be set via a `function` reference. This means you cannot use them in plain JSON.

#### Expected behavior

I'd like to register these like I do custom widgets/fields.

```js
const table = (props) => { ...a component that renders a <table> with rows... };

const templateFields = { table };

const uiSchema = {
  "ui:ArrayTemplateField": "table"
}

render((
  <Form
    schema={schema}
    uiSchema={uiSchema}
    templateFields={templateFields} />
), document.getElementById("app"));
```

#### Actual behavior

Not possible, you must do this:

```js
const table = (props) => { ...a component that renders a <table> with rows... };

const uiSchema = {
  "ui:ArrayFieldTemplate": table  // HAVE TO USE FUNCTION REFERENCE
}

render((
  <Form
    schema={schema}
    uiSchema={uiSchema} />
), document.getElementById("app"));
```
### Version

1.8.0

### PR DESCRIPTION
**Pull request by AdelRashed97**
Reasons for making this change
At moment the only way to have multiple ArrayFieldTemplates and ObjectFieldTemplates is to pass a React component through the uiSchema. This is limiting especially if the schema is to be generated from the backend and sent as a json to the front end.

I have added two optional props arrayFieldTemplates and objectFieldTemplates. Both props are dictionary. The user then specify the template to use in uiSchema by a string.

fixes #1680 

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by AdelRashed97** [comment]
@epicfaace it will be great if we can get this feature out as soon as possible. My company use rjsf and we need this feature

**Comment by AdelRashed97** [comment]
@epicfaace  can I get a review

**Comment by AdelRashed97** [comment]
@agustin107 can you review

**Comment by epicfaace** [comment]
Hey -- why did you close this PR? Are you still interested in getting this in?

**Pull request closed without merging**
