### PR TITLE
Bug/add nofill option

### LINKED ISSUE #1026: Cannot default array of objects to an empty array
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When creating an array of objects using minItems there is no way to default the array to an emtpy array. If the array is empty the package with fill it with the structure of the object with all of its keys having values of `undefined`.

### Steps to Reproduce

[Shared playground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsibGlzdE9mT2JqZWN0cyJdLCJwcm9wZXJ0aWVzIjp7Imxpc3RPZk9iamVjdHMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBIGxpc3Qgb2Ygc3RyaW5ncyIsImRlZmF1bHQiOltdLCJtaW5JdGVtcyI6MSwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiaWQiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiaWQiXX19fX0sInVpU2NoZW1hIjp7Imxpc3RPZlN0cmluZ3MiOnt9LCJtdWx0aXBsZUNob2ljZXNMaXN0Ijp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifSwiZml4ZWRJdGVtc0xpc3QiOnsiaXRlbXMiOlt7InVpOndpZGdldCI6InRleHRhcmVhIn0seyJ1aTp3aWRnZXQiOiJzZWxlY3QifV0sImFkZGl0aW9uYWxJdGVtcyI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24ifX0sInVub3JkZXJhYmxlIjp7InVpOm9wdGlvbnMiOnsib3JkZXJhYmxlIjpmYWxzZX19LCJ1bnJlbW92YWJsZSI6eyJ1aTpvcHRpb25zIjp7InJlbW92YWJsZSI6ZmFsc2V9fSwibm9Ub29sYmFyIjp7InVpOm9wdGlvbnMiOnsiYWRkYWJsZSI6ZmFsc2UsIm9yZGVyYWJsZSI6ZmFsc2UsInJlbW92YWJsZSI6ZmFsc2V9fSwiZml4ZWROb1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19fX0=)

#### Expected behavior

When an array of objects has a `default` value of `[]` and `minItems` set higher than 1 it should default to an empty array with a validation error saying that the array must have at least `minItems`.

#### Actual behavior

`minItems` number of empty objects are injected into the array to satisfy the `minItems` constraint. If the object has any required fields validation with throw an error about the empty object not having that field instead of the array not having enough items.

### Version

`1.0.4`

### PR DESCRIPTION
**Pull request by conord33**
### Reasons for making this change

Fixes #1026 

I am not exactly sure if this breaks some kind of json schema spec, but this seemed like the best way to fix this issue while still maintaining backwards compatibility.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated docs if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by edi9999** [comment]
noFill should not be defined in the schema but rather in the uiSchema.

**Comment by conord33** [comment]
good point, i will see if i can easily make that change

**Comment by glasserc** [comment]
I'd like to merge a change like this. Why do we have to use `schema.default`? Why can't we just use whatever the current `formData` value is?

**Comment by epicfaace** [comment]
@conord33 are you still able to work on this PR and move `noFill` over to the uiSchema?

**Comment by conord33** [comment]
@epicfaace sorry I have not had time to jump back into this PR. And probably wont for another week or so 😞

**Pull request closed without merging**
