### PR TITLE
Do not pass hideError prop to material components. fixes #3945

### LINKED ISSUE #3945: Error: React does not recognize the `hideError` prop on a DOM element
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.13.6

### Current Behavior

Starting at 5.13.6 I get the following error in the console:
```
Warning: React does not recognize the `hideError` prop on a DOM element
```

I didn't investigate it further aside from the fact that this error doesn't happen on 5.13.5 and that most likely it is coming from 
`packages/mui/src/BaseInputTemplate/BaseInputTemplate.tsx` where `hideError` is not being extracted from `props`.

### PR DESCRIPTION
**Pull request by ValYouW**
### Reasons for making this change
Fixes #3945

### CODE REVIEW

**Comment by heath-freenome** [comment]
@ValYouW Can you please update the `5.14.1` section of the `CHANGELOG.md` file indicating this fix for the two themes, thanks!

**Comment by ValYouW** [comment]
@heath-freenome pushed changelog, hope the format is ok

**Comment by heath-freenome** [comment]
> @heath-freenome pushed changelog, hope the format is ok

Looks good! Please resolve the conflicts

**Comment by ValYouW** [comment]
> > @heath-freenome pushed changelog, hope the format is ok
> 
> Looks good! Please resolve the conflicts

fixed

**Review by heath-freenome — APPROVED** [review]

**Pull request merged**
