### PR TITLE
correct antd SelectWidget filter option check. fix PR #3377

### PR DESCRIPTION
**Pull request by hextion**
Hello everyone

Filtering made in #3377 isn't working because `Select.Option` doesn't have `label` prop passed into.
So I fixed that

### CODE REVIEW

**Comment by hextion** [comment]
@nickgros review please

**Comment by heath-freenome** [comment]
@hextion Can you please update the `CHANGELOG.md` with a description of your fix:
```
# 5.13.3

## @rjsf/antd

- <your fix description>
```

**Comment by heath-freenome** [comment]
> @hextion Can you please rebase and update the `CHANGELOG.md` with a description of your fix:
> 
> ```
> # 5.13.3
> 
> ## @rjsf/antd
> 
> - <your fix description>
> ```

Nevermind, I'm pushing a fix today and will update the changelog

**Review by heath-freenome — APPROVED** [review]

**Comment by hextion** [comment]
@heath-freenome sorry I was out of town so I couldn't do stuff. thank you for accepting PR, really appreciate it

**Pull request merged**
