### PR TITLE
Fix: Localization for error messages

### PR DESCRIPTION
**Pull request by Ugolaf**
### Reasons for making this change

[Please describe them here]

If this is related to existing tickets, include links to them as well. Use the syntax `fixes #[issue number]` (ex: `fixes #123`).

### Checklist

* [x] **I'm updating documentation**
  - [x] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/master/CHANGELOG.md) with a description of the PR
* [x] **I'm adding a new feature**
  - [x] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by Ugolaf** [comment]
Sorry it's a fail, I wanted to remove merge conflicts from https://github.com/rjsf-team/react-jsonschema-form/pull/2189.

**Comment by Ugolaf** [comment]
@epicfaace can you review this one ?

**Comment by Ugolaf** [comment]
@epicfaace How can I add you as a reviewer?

**Comment by MedinaGitHub** [comment]
how can i help with this topic?

**Comment by Ugolaf** [comment]
I pulled v4 into my fork. @epicfaace can you review it ?

**Comment by epicfaace** [comment]
Thanks for your work on this PR! Can you add it to the agenda https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit so we can schedule a synchronous review?

**Comment by heath-freenome** [comment]
@Ugolaf So this work has been completed in a different way in the v5 beta as part of this [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/3093). If you agree with me, please close your PR...

**Pull request closed without merging**
