### PR TITLE
fix placeholder not being passed to inputs across most themes

### LINKED ISSUE #2091: [bootstrap-4] ui:placeholder isn't rendered for <input>
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using the `bootstrap-4` theme, `placeholder` attributes on text inputs aren't rendered.

### Steps to Reproduce

1. [Playground link]https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTpwbGFjZWhvbGRlciI6InBsYWNlaG9sZGVyIGZvciBmaXJzdCBuYW1lIn19LCJ0aGVtZSI6ImJvb3RzdHJhcC00IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

#### Expected behavior

The "First Name" input is rendered with a placeholder.

#### Actual behavior

The "First Name" input is rendered without a placeholder.

### Version

`master`

### LINKED ISSUE #2092: [fluent-ui] ui:placeholder isn't rendered for <input>
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using the `fluent-ui` theme, `placeholder` attributes on text inputs aren't rendered.

### Steps to Reproduce

1. [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTpwbGFjZWhvbGRlciI6InBsYWNlaG9sZGVyIGZvciBmaXJzdCBuYW1lIn19LCJ0aGVtZSI6ImZsdWVudC11aSIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

#### Expected behavior

The "First Name" input is rendered with a placeholder.

#### Actual behavior

The "First Name" input is rendered without a placeholder.

### Version

`master`

### LINKED ISSUE #2093: [semantic-ui] ui:placeholder isn't rendered for <input>
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using the `semantic-ui` theme, `placeholder` attributes on text inputs aren't rendered.

### Steps to Reproduce

1. [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTpwbGFjZWhvbGRlciI6InBsYWNlaG9sZGVyIGZvciBmaXJzdCBuYW1lIn19LCJ0aGVtZSI6InNlbWFudGljLXVpIiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

#### Expected behavior

The "First Name" input is rendered with a placeholder.

#### Actual behavior

The "First Name" input is rendered without a placeholder.

### Version

`master`

### LINKED ISSUE #2094: [fluent-ui] ui:placeholder isn't rendered for <textarea>
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using the `fluent-ui` theme, `placeholder` attributes on textarea inputs aren't rendered.

### Steps to Reproduce

1. [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSIsInVpOnBsYWNlaG9sZGVyIjoicGxhY2Vob2xkZXIgZm9yIGZpcnN0IG5hbWUifX0sInRoZW1lIjoiZmx1ZW50LXVpIiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

#### Expected behavior

The "First Name" textarea is rendered with a placeholder.

#### Actual behavior

The "First Name" textarea is rendered without a placeholder.

### Version

`master`

### PR DESCRIPTION
**Pull request by Hasenn**
### Reasons for making this change

I need it to work with bootstrap-4
should fix issues #2094 #2093 #2092 #2091

fixes #2094  fixes #2093 fixes #2092 fixes #2091

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [x] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by Hasenn** [comment]
There are loads of tests to update apparently, if someone more familiar with this repo could do it i'ld appreciate it. otherwise i will probably have to do it at some point. the test expect a snapshot of the html to match the generated one so they complain about the placeholder prop being there --'

**Comment by mdornseif** [comment]
https://github.com/mdornseif/react-jsonschema-form/commit/4c1fc8cf50fb64e79741cc8b0fda1430702adb56 fixes the tests. I can not commit to this PR.

You can get it with
```
git remote add mdornseif https://github.com/mdornseif/react-jsonschema-form.git
git fetch mdornseif
git cherry-pick 4c1fc8c
```

**Comment by ssbyoung** [comment]
@Hasenn Any chance of this getting merged soon? If not I can try to get an up to date version of this branch sometime next week.

**Comment by Hasenn** [comment]
@ssbyoung I commited mdornseif's fix, if it passes tests it might get merged

**Comment by Hasenn** [comment]
@agustin107 this should be ready to merge

**Comment by ssbyoung** [comment]
@epicfaace can you take a look at this? I think @agustin107 is away.

**Review by epicfaace — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
