### PR TITLE
Autocomplete functionality with test

### LINKED ISSUE #906: Support for input 'autocomplete' attribute?
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

It looks like setting `autocomplete` attribute for inputs is not supported (without writing a custom component).

It would help to improve usability of forms. See for example a nice [Google Developer](https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#recommended_input_name_and_autocomplete_attribute_values) post.

### How to implement
I think it could be added like `autofocus` [got added](https://github.com/mozilla-services/react-jsonschema-form/commit/316258ea5f9ef8b0c03c9e4db991029e2c164428). Is this the best way to do it?

### PR DESCRIPTION
**Pull request by sramaswami11**
### Reasons for making this change

fixes #906

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
@sramaswami11 can you please fix the failing test on CI?

**Comment by epicfaace** [comment]
How to revert a single file:

```
git fetch # download latest changes to origin/master
git checkout origin/master -- package.json # reset your package.json to the package.json that is in origin/master
git add package.json
git commit -m "removed file"
git push
```

**Comment by sramaswami11** [comment]
Removed the package..lock.json that were added inadvertently.

**Comment by epicfaace** [comment]
Actually, we're ok. Thanks!

**Comment by uwolfer** [comment]
Thanks for your work! Is this something you also want to add to the docs?

**Pull request merged**
