### PR TITLE
fix: set defaults for oneOf + ref

### LINKED ISSUE #3633: Default values are not set for oneOf + ref in schema
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.6.0

### Current Behavior

I have a schema of a `oneOf` with two options referencing two different objects.

Here is an example:

```
{
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "fooProp": {
          "type": "string"
        },
        "fooProp2": {
          "type": "string",
          "default": "fooProp2"
        }
      }
    },
    "bar": {
      "type": "object",
      "properties": {
        "barProp": {
          "type": "string"
        },
        "barProp2": {
          "type": "string",
          "default": "barProp2"
        }
      }
    }
  },
  "oneOf": [
    {
      "$ref": "#/definitions/foo"
    },
    {
      "$ref": "#/definitions/bar"
    }
  ]
}
```

You can try it out [here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJmb28iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vUHJvcCI6eyJ0eXBlIjoic3RyaW5nIn0sImZvb1Byb3AyIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiZm9vUHJvcDIifX19LCJiYXIiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYmFyUHJvcCI6eyJ0eXBlIjoic3RyaW5nIn0sImJhclByb3AyIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiYmFyUHJvcDIifX19fSwib25lT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL2ZvbyJ9LHsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvYmFyIn1dfSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).

### Expected Behavior

I would expect to have a default prop set for the properties that define one.

### Steps To Reproduce

1. Just go to the playground link provided in the description
2. You will be able to see that in the _formData_ we don't have the default value set

### Environment

```markdown
- OS: MacOs
- Node: 18.7.0
- npm: 8.15.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by anthonycaron**
### Reasons for making this change

fixes #3633

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [x] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
@anthonycaron There is another PR that will be merged in the next day or so in the same file. Since this one has been going through a few rounds of reviews already, I will wait to review this after we merge that one and you rebase and fix the conflicts that will be coming.

**Comment by heath-freenome** [comment]
@anthonycaron The PR was merged. Please rebase and take care of the conflicts! Thanks

**Comment by anthonycaron** [comment]
@heath-freenome Done !

**Comment by heath-freenome** [comment]
@anthonycaron This looks great! One last thing, if you can remove the update to the `package-lock.json` file I would appreciate it. It will be updated by the publishing process anyway.

**Review by heath-freenome — APPROVED** [review]

**Comment by anthonycaron** [comment]
@heath-freenome Thanks ! Do you have an idea when the next release will happen ?

**Comment by heath-freenome** [comment]
@anthonycaron I'm hoping to get it released soon after I get #3652 merged

**Pull request merged**
