### PR TITLE
Use PNPM Workspace

### PR DESCRIPTION
**Pull request by ahkhanjani**
### Reasons for making this change

Try to implement #3382

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by heath-freenome** [comment]
This seems similar to the [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/3382) that @nickgros pushed to try and get things working. Maybe you two can get it working?

**Comment by heath-freenome** [comment]
@ahkhanjani Any luck figuring this out?

**Comment by heath-freenome** [comment]
@ahkhanjani How are things in your world? You've been quiet of late

**Comment by ahkhanjani** [comment]
@heath-freenome Hi! Long time no see. I'm the only developer in our startup currently and we're close to lunch. Exciting yet time consuming. I apologize for these open PRs. I will prioritize them as soon as I have time for side projects. I'm fascinated by this project and want to contribute to it. I will let you know. Thank you for your patience 🌹

If the changes get too complex I'll start from scratch so no worries about that. I'll close the PRs for the time being

**Pull request closed without merging**
