### PR TITLE
Allow additionalProperties 0 value

### LINKED ISSUE #2462: additionalProperties [number] doesn't allow 0 values
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If I define a schema with "additionalProperties" with number values, I cannot set field to be 0 (gets set as empty string instead). All other numbers work fine.

**Edit:** This is also true of boolean additionalProperties set to false.

Example schema:
```
{
  "type": "object",
  "additionalProperties": {
    "type": "number"
  }
}
```

[playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJrZXkiOiIifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJ0eXBlIjoibnVtYmVyIn19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUifSwibGFzdE5hbWUiOnsidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

### Steps to Reproduce

- Add new key/value pair
- Defaults to 0, this is fine
- Change to non-zero value
- Try changing back to 0: Doesn't work

#### Expected behavior

Would like to set value to 0

#### Actual behavior

Field is set as empty string

### Version

2.5.1, though this also occurs in rjsf playground

### PR DESCRIPTION
**Pull request by debevoise**
### Reasons for making this change

[fixes #2462](https://github.com/rjsf-team/react-jsonschema-form/issues/2462)

`onPropertyChange` event handler checks if value is falsey (assuming its undefined) and consequently rejects intended 0 values. Adding additional check for number to prevent unintended behavior.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by epicfaace — COMMENTED** [review]
Would it be valid if value were also equal to other falsey numbers such as "null"?

**Comment by debevoise** [comment]
> Would it be valid if value were also equal to other falsey numbers such as "null"?

Not within this event handler, because `typeof null !== "number"` in this case (`=== "object"` instead).

**Comment by epicfaace** [comment]
> Let me know if this is what you meant, or if you want to see tests for preexisting `formData` with additionalProperties being set to null values (or other falsey values)

Oh, what I meant is -- is there another issue similar to yours which involves `null` values for additionalProperties instead of `0`?

**Comment by debevoise** [comment]
> Oh, what I meant is -- is there another issue similar to yours which involves null values for additionalProperties instead of 0?

Ok, apologies for the delay in updating, but yes that is a concern. I tried setting boolean additional properties, and `false` values also default to empty string. Really, per the comment (`Don't set value = undefined for fields added by  additionalProperties`), the only value we want to avoid is `undefined` itself as `0, "", false, null` are valid json values. So just checking if `value === undefined` would suffice.

**Review by epicfaace — COMMENTED** [review]
Thanks, this looks good. Can you add a test that ensures we can add 0 values to additionalProperties (as well as other falsey values such as `null`)?

**Comment by debevoise** [comment]
Yes, sorry to be a bother, but I've been having trouble running tests. From master:
```
node -v  // v16.4.2
npm i
npm test
```
Most tests run, but I do get the below issue for some of them: I assume I need a polyfill to access `requestAnimationFrame` from a non-browser environment
```
@rjsf/core:   1) anyOf
@rjsf/core:        should assign a default value and set defaults on option change:
@rjsf/core:      TypeError: requestAnimationFrame is not a function
```

**Comment by epicfaace** [comment]
Try using node 14

**Comment by verakruhliakova** [comment]
@epicfaace @debevoise Hello guys, are there any news on this bug? I just want to link related PR with same changes and with tests, it is here - https://github.com/rjsf-team/react-jsonschema-form/pull/2540 Hope it will help to progress on the fix 🙏

**Comment by epicfaace** [comment]
closing in favor of https://github.com/rjsf-team/react-jsonschema-form/pull/2540/

**Pull request closed without merging**
