### PR TITLE
Update react peer dependency to be 16.8.0 so hooks can be used in this repo.

### LINKED ISSUE #2449: ui:emptyValue does not work when initial data has an empty string
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The method of providing a default value, putting a `ui:emptyValue` in the uiSchema does not fill out a default value.

SSCCE 
[rjsf-empty-value-issue.zip](https://github.com/rjsf-team/react-jsonschema-form/files/6735809/rjsf-empty-value-issue.zip)

empty value does not work

### Steps to Reproduce

1. Use ui:emptyValue

#### Expected behavior

The form should have the value of ui:emptyValue if the property is falsey.

#### Actual behavior

Form is still empty

### Version

3.0.0

### PR DESCRIPTION
**Pull request by ssbyoung**
### Reasons for making this change

I am planning on making a change to fix #2449. Want to be able to use hooks in the feature I'm writing.

### Checklist

* [X] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [X] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed

### CODE REVIEW

**Comment by epicfaace** [comment]
This would probably be a breaking change, though.

**Comment by ssbyoung** [comment]
@epicfaace all of the packages under the covers are developing against at least 16.8.0. I initially tried to upgrade to react 17, but I think there are issues with `ReactIs.isMemo` in core that were giving me headaches.

**Comment by epicfaace** [comment]
Could you clarify what you meant by "all of the packages under the covers"?
Not quite sure what you meant.

--
Ashwin Ramaswami

**Comment by ssbyoung** [comment]
@epicfaace all of the package.json for the individual packages have react as a dev dependency that is at least 16.8.0:

https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/antd/package.json#L66
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/bootstrap-4/package.json#L38
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/package.json#L92
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/fluent-ui/package.json#L42
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/package.json#L37
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/playground/package.json#L103
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/semantic-ui/package.json#L77

My understanding of this means that all the tests and development are happening on react versions that are at least 16.8.0.

**Comment by ssbyoung** [comment]
@epicfaace what is the best way to get my PR's in front of reviewers?

**Comment by epicfaace** [comment]
@ssbyoung See https://github.com/rjsf-team/react-jsonschema-form/issues/2418!

As for https://github.com/rjsf-team/react-jsonschema-form/issues/2449, it's going to take longer to merge / release if it requires bumping a peer dependency -- i.e., it would need to wait until v4, which might take a couple months at least. Is hooks the only way to do it?

**Comment by ssbyoung** [comment]
Closing this PR as the one that requires it is no longer needed.

**Pull request closed without merging**
