### PR TITLE
Fix/semantic custom fields

### PR DESCRIPTION
**Pull request by jacqueswho**
### Reasons for making this change

Fix related to issue [1946](https://github.com/rjsf-team/react-jsonschema-form/issues/1946)

Features:
- Semantic updated to 1.2.1
- getSemanticProps to allow user pass semantic ui props including defaults
- added submitButton
- added Date and DateTime Widgets
- added email Widget
- getSemanticErrorProps to allow user to pass ui error props
- implement getDisplayLabel from core/utils
- added URLWidget

Fixes:
- Semantic documentation updates
- checkbox widget to use label or schema title
- select widget to use label or schema title
- textarea widget to use label or schema title
- text widget to use label or schema title

If this is related to existing tickets, include links to them as well.

### Checklist

* [x] **I'm updating documentation**
  - [x] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [x] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Review by jacqueswho — COMMENTED** [review]
updated  semantic
formContext props should over rider others

**Comment by jacqueswho** [comment]
@epicfaace can I merge this in?

**Comment by epicfaace** [comment]
Sorry for the delay @jacqueswho. Could you update the PR description with a list of what features / changes exactly this PR adds? This PR seems pretty big and probably does more than just fix #1946.

**Comment by jacqueswho** [comment]
> Sorry for the delay @jacqueswho. Could you update the PR description with a list of what features / changes exactly this PR adds? This PR seems pretty big and appears to do more than just fix #1946 (such as adding new widgets).

@epicfaace done

**Comment by jacqueswho** [comment]
@epicfaace please check and approve if happy.  What is the rule of thumb, do I merge after approval or the approver?

**Comment by jacqueswho** [comment]
@epicfaace is there anything else?

**Comment by epicfaace** [comment]
I'll take a look, sorry for the delay

**Comment by jacqueswho** [comment]
@epicfaace is this project still being maintained? no activity

**Comment by epicfaace** [comment]
Yes. @jacqueswho do you mind splitting this PR into separate PRs, one for each feature (for example, you could split it into one PR for the label / schema title fixes, one PR for the semantic update, one PR for each new widget)? That way, I'll be able to more easily tell which code fixes which issue, as it's not entirely clear from looking at this large, entire PR. The only PRs that make lots of unrelated changes should be the PRs that introduce a new theme (as that's unavoidable). That's the main reason I haven't been able to get to it, sorry for not letting you know about this earlier.

**Comment by jacqueswho** [comment]
> Yes. @jacqueswho do you mind splitting this PR into separate PRs, one for each feature (for example, you could split it into one PR for the label / schema title fixes, one PR for the semantic update, one PR for each new widget)? That way, I'll be able to more easily tell which code fixes which issue, as it's not entirely clear from looking at this large, entire PR. The only PRs that make lots of unrelated changes should be the PRs that introduce a new theme (as that's unavoidable). That's the main reason I haven't been able to get to it, sorry for not letting you know about this earlier.

@epicfaace  this is going to be tricky, as the reason I included the new widgets with this pull request is I had to change the method getSemanticProps, which made me change how to pass the props in all the components, to follow the same approach.  Its honestly going to be too much to change to make it separate. I have also been constantly waiting, and trying to merge with master to make sure it is up to date. Its almost been a month. I really am sorry, but I did not want to create separate pull requests to fix the other issues mentioned because of this change in every component how the props have been passed. Could we please just merge this in. In future the pull requests will be smaller. The main change this pull request, does is fix the issue of custom semantic props being passed properly. But I do think we should make this in core, and other themes just pass in their key that is related to finding the props

**Comment by epicfaace** [comment]
Sorry man, but I think splitting them up is the best way to ensure there aren't any regressions and that we agree on the substantial changes to the codebase that are made in this PR. Also, sometimes open source just takes a while (months / years) because people work for free 😉 . Totally get that you're probably tired waiting for this PR to get reviewed, but I do want this PR to get in, so I'm happy to help with the work of splitting this up -- perhaps I can make the split-up PRs and then you can review them?

I think the first thing I'd like to do is make a PR with just the new `getSemanticProps` and `getSemanticErrorProps` functions. However, it wasn't super clear to me what they are doing with the changes in this PR. Do you mind explaining a bit more what these functions are doing and how the new behavior differs from the old `getSemanticProps` function? Additionally, what's the rationale behind moving default props from declaring something like `CheckboxWidget.defaultProps` to `defaultSchemaProps`?

**Comment by jacqueswho** [comment]
@epicfaace I have done as you asked except for the function change pr
https://github.com/rjsf-team/react-jsonschema-form/pull/2226
https://github.com/rjsf-team/react-jsonschema-form/pull/2225
https://github.com/rjsf-team/react-jsonschema-form/pull/2224

regarding the function changes needed. default props does not work as intended, because if props are passed including the uiOptions with semantic props, it works fine. However if the user just adds one semantic prop, all the default props are lost. So I have changed the semantic functions to cater for this. If the user includes a new semantic prop that is not the default, they are not lost, but if they include on that is changing the defaults it will do so. So I feel all themes are going to have this issue, so we should maybe include this function in core utils. you pass the uiSchema and include your theme specific key and defaults

**Comment by epicfaace** [comment]
@jacqueswho wow, thanks so much for doing this! I'll take a look.

**Comment by epicfaace** [comment]
Closing this PR in favor of the PRs mentioned above that it's split up into.

**Pull request closed without merging**
