### PR TITLE
Fix race condition for onChange when formData is controlled prop

### PR DESCRIPTION
**Pull request by olzraiti**
### Reasons for making this change

This bug was introduced by #1804

The race condition occurs when (1) Form receives the `formData` prop, and will call the `onChange` function, and (2) when `onChange` is called at the same time by some component rendered by the Form.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by olzraiti** [comment]
The test is passing in the latest version, closing.

**Comment by epicfaace** [comment]
Huh, I wonder what might have fixed it... good it's fixed though! :)

**Comment by olzraiti** [comment]
Hmm, though after upgrading to the latest rjsf version, my tests broke - adding this patch again fixed the tests... There's something that the test doesn't catch.

**Comment by epicfaace** [comment]
hmm, do you want to try adding a better test that catches this bug (or perhaps it's a new bug)?

**Pull request closed without merging**
